HW7 is completed
Grog2903/hw pull request #7
Opened 2024-10-30 18:00 UTC by Grog2903

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-10-31 17:38 UTC, vladislavmass requested changes

2024-10-31 17:38 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if err != nil {
Почему мы пропускаем подробности ошибки? Как понять причину ошибки?

2024-10-31 17:38 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	tmpFile, err := os.CreateTemp("./", "e-*.txt")
По заданию у нас не указано что мы работаем только с текстовыми файлами, поэтому код должен работать как с текстовыми файлами, так и с любыми другими файлами

2024-10-31 17:38 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	tmpFile, err := os.CreateTemp("./", "e-*.txt")
А если я копирую с корня диска с, в папку на диск D, то 1) Мне может быть отказано в доступен 2) на диске С может не быть нужного объема памяти

2024-10-31 17:38 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	destinationFile, err := os.Create(toPath)
Зачем копировать еще раз, почему нельзя просто переименовать?

2024-11-02 12:59 UTC, Grog2903 commented on hw07_file_copying/main.go
>  func main() {
d

2024-11-03 11:39 UTC, vladislavmass approved these changes

2024-11-07 19:20 UTC, merged